name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 10 * * *'

jobs:
  flutter:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        channel:
          # - beta # too different from stable, thus analyzer will complain
          - stable
        package_name:
          - convenient_test
          - convenient_test/example
          - convenient_test_common
          - convenient_test_common_dart
          - convenient_test_dev
          - convenient_test_manager
          - convenient_test_manager_dart

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Install dependencies
        run: flutter pub get
        working-directory: packages/${{ matrix.package_name }}

      - name: Analyze
        run: flutter analyze
        working-directory: packages/${{ matrix.package_name }}

      - name: Dart code metrics
        run: flutter pub run dart_code_metrics:metrics analyze lib --fatal-style --fatal-performance --fatal-warnings --set-exit-on-violation-level noted
        working-directory: packages/${{ matrix.package_name }}

      - name: Run tests
        run: flutter test
        working-directory: packages/${{ matrix.package_name }}

      - name: Check format
        run: flutter format --set-exit-if-changed --line-length 120 .
        working-directory: packages/${{ matrix.package_name }}


  build_manager_macos:
    runs-on: macOS-11

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64
      
      - name: Enable Macos
        run: flutter config --enable-macos-desktop

      - name: Install dependencies
        run: flutter pub get
        working-directory: packages/convenient_test_manager

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'

      - name: setup-cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: latest

      - name: flutter build
        run: flutter build macos
        working-directory: packages/convenient_test_manager/macos

      - name: build_mac_app
        run: bundle install && bundle exec fastlane run build_mac_app export_method:mac-application scheme:Runner output_directory:./build
        working-directory: packages/convenient_test_manager/macos

      - name: Tar outputs
        run: cd packages/convenient_test_manager/macos/build && tar cvf convenient_test_manager.app.tar convenient_test_manager.app

      - uses: actions/upload-artifact@v3
        with:
          name: manager_macos
          path: packages/convenient_test_manager/macos/build/convenient_test_manager.app.tar

          
  build_manager_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Enable Linux
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libvlc-dev vlc
          flutter config --enable-linux-desktop
        working-directory: packages/convenient_test_manager

      - name: Install dependencies
        run: flutter pub get
        working-directory: packages/convenient_test_manager

      - name: flutter build
        run: flutter build linux
        working-directory: packages/convenient_test_manager

      - name: Tar outputs
        run: tar -czvf convenient_test_manager.tar.gz -C packages/convenient_test_manager/build/linux/x64/release/ bundle

      - uses: actions/upload-artifact@v3
        with:
          name: manager_linux
          path: convenient_test_manager.tar.gz

  build_manager_headless_cli:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Install dependencies
        run: dart pub get
        working-directory: packages/convenient_test_manager_dart

      - name: Dart Compile
        run: |
          dart compile exe ./bin/convenient_test_manager_dart.dart -o manager_headless
          dart compile kernel ./bin/convenient_test_manager_dart.dart -o manager_headless_kernel
        working-directory: packages/convenient_test_manager_dart

      - uses: actions/upload-artifact@v3
        with:
          name: manager_linux-mac_headless_cli
          path: packages/convenient_test_manager_dart/manager_headless

      - uses: actions/upload-artifact@v3
        with:
          name: manager_headless_kernel
          path: packages/convenient_test_manager_dart/manager_headless_kernel
